#!/usr/bin/perl -w

use strict;

# parse param
my $argc = @ARGV;
die "Usage: $0 <Organism name>" unless $argc == 1;
my $organismName = $ARGV[0];

$organismName =~ s/\s/_/g;;
print "try downloading $organismName ...\n";

# Donwload the genome report

my $serverName = "ftp.ncbi.nlm.nih.gov";
my $loginName = "anonymous";
my $loginPassword = "";

use LWP::Simple;
use Net::FTP;
# open connection
my $ftp = Net::FTP->new($serverName, Debug => 0, Passive => 1) or die "unable to connect ftp://$serverName/: $@\n";
$ftp->login($loginName, $loginPassword);
$ftp->cwd("/genomes/Bacteria") or die "FATAL ERROR: couldn't change directory ".$ftp->message."\n";
# list all files
my $taxaFound = "false";
my @files = $ftp->ls;
for my $file (@files) {
  if ($file =~ m/($organismName)/i) { # eq organism
    $taxaFound = "true";
    # cwd to organismus dir
    $ftp->cwd("./$file") or die "Couldn't open $organismName directory: ".$ftp->message."\n";
    my @organismFiles = $ftp->ls;
    # save Data
    my $proteins = "false";
    my $genomes = "false";
    my $orfs = "false";
    for (@organismFiles) {
      if ($_ =~ m/\.faa/i) {
        $ftp->get($_,"Proteins.txt") or die $ftp->message;
        $proteins = "true";
      }
      elsif ($_ =~ m/\.fna/i) {
        $ftp->get($_,"Genomes.txt") or die $ftp->message;
        $genomes = "true";
      }
      elsif ($_ =~ m/\.Glimmer3/i) {
        $ftp->get($_,"ORFs.txt") or die $ftp->message;
        $orfs = "true";
      }
    }
    # errors/warnings
    if($proteins eq "false") {
      print "failed to save Proteins.txt\n";
    }
    if($genomes eq "false") {
      print "failed to save Genomes.txt\n";
    }
    if($orfs eq "false") {
      print "failed to save ORFs.txt\n";
    }
  }
}
# quit
$ftp->quit();
# organismus not found
if($taxaFound eq "false") {
  print "Organism not found!\n"
} else {
  print "Organismdata successfully downloaded!\n";
}

