#!/usr/bin/perl -w

use strict;

# parse param
my $argc = @ARGV;
die "Usage: $0 <Organism name>" unless $argc == 1;
my $organismName = $ARGV[0];

# Donwload the genome report
use LWP::Simple;
my $genomeContent= `wget -qO- ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt`;
die "Could not download prokaryote info URL from NCBI server!\n" unless $genomeContent;


my $prokaryoteInfoUrl = "ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt";
my $genomeContent = get $prokaryoteInfoUrl

#Find the line(s) with the organism
foreach my $line (split /\n/ ,$genomeReport) {
	if($line =~ m/^\Q$organismName\E\t/) {
print $line;
		if($line =~ m/^([^\t]+\t){5}([\d.]+)/) {
			print "Genome of '$organismName' has length $2 Mb\n";
		}
	}
}
