/*
 * This is a simple Reader, to read in the dssp-file generated by the python script.
 */
package de.bioinformaikmuenchen.pg4.ssp.ssptrain;

// imports
import java.io.File;

/**
 * 
 * @author spoeri
 */
public class Reader {
    
    /**
     * Constructor
     * 
     * 
     */
    public Reader(File toImport) {
      
    }
    
    
}
