#! /usr/bin/perl -w
#warnings, newlines
use strict;
use LWP::Simple;

print "Enter query for uniprot, you will receive the number of results:";
my $line = <STDIN>;
chomp $line;

my $html = get("http://www.uniprot.org/uniprot/?query=".$line);
my @chars = split("", $html);
my $subs;
if($html =~ m/of <strong>.+<\/strong> result/){
	my $regexLocation = $-[0];
	for(my $i=$regexLocation+10;$i<$regexLocation+30;$i++){
		$subs.=$chars[$i];
	}
	
}
$html =~ m/of <strong>.+<\/strong> result/;
#print $-[0]." bis ".$+[0];
#print $subs;
$subs =~ m/(\d+,?)+/;
if(!$line) {
	$line = "<no filter>";
}
print "Searching for $line yields ".substr($subs,$-[0],$-[0]+$+[0]-2)." results\n";
