package de.bioinformatikmuenchen.pg4.validation;

/**
 *
 *
 */
public class App {

    public static void main(String[] args) {
        String a1 = "VBSD--EFG";
        String b1 = "L-MNOPQR-";
        String c1 = "-VB-SDE-FG";
        String d1 = "LMNOP-QR--";

        String a2 = "QW-ERTA";
        String b2 = "--MORTA";
        String c2 = "QW--ERTA";
        String d2 = "-MOR--TA-";

        String a3 = "RO-FLMA-O";
        String b3 = "-GN_AALOL";
        String c3 = "ROFL-MAO";
        String d3 = "GNAALO-L";

        String a4 = "EKSVVFKAEGEHFTDQKGNTIVGSGSGGTTKYF-------RIPAM--CTTSKGTIVVFADARHNTASDQSFIDTAAA---RSTDGGKTWNKKIAIYNDRVNSKLSRVMDPTCIVANIQGRETILVMVGKWNNNDKTWGAYRDKAPDTDWDLVLYKSTDDGVTFSKVETNIHDIVTKNGTISAMLGGVGSGLQL---------NDGKLVFPVQMVRTKNITTVLNTSFIYSTD-GITWSLPSGYCEGF------------GSENNIIEF-NASLVNNIR----------NSGLRRSFETKDFGKTWTEFPPMDKKV-DNRNHGVQGSTIT---IPSGNKLVAAHSSAQNKNNDYTRSDISL---YAHNL-YSGEVKLIDDFYPKVGNASGAGYSCLSYRKNVDKETLYVVYEANGSIEFQDLSRHLPVIKSYN--------";
        String b4 = "---------------------------------VIFRGPDRIPSIVASSVTPGVVTAFAEKRVGGGDPGALSNTNDIITRTSRDGGITWDTELNLTEQINVSDEFDFSDPRPIYD--PSSNTVLVSYARWPTDAA-----QNGDRIKPW-------MPNGIFYS-----VYDVASGNWQAPIVNPGPGHGITLTRQQNISGSQNGRLIYPA-IVLDRFFLNVMS---IYSDDGGSNWQTGSTLPIPFRWKSSSILETLEPSEADMVELQNGDLLLTARLDFNQIVNGVNYSPRQQFLSKDGGITWSLLEANNANVFSNISTGTVDASITRFEQSDGSHFLLFTNPQGNPAGTNGRQNLGLWFSFDEGVTWKGPIQLVN---------GASAYSDI-YQ--LDSENAIVIVETDNS-NMRILRMPITLLK---QKLTLSQN";
        String c4 = "EKSVVFKAEGEHFTDQKGNTIVGSGSGGTTKYFRIPAMCTTSK--GTIVVFADARHNTASDQ---SFIDTAAARSTDGGKTW-NKKIAIYNDRVNSKLSRVMDPTCIVANIQGRETILVMVGKWNNNDKTWG--AYRDKAPDT--DWDLVLYKSTDDGVTFSKVETNIHDIVTKNGTISAMLGGVGSGLQLN---------DGKLVFPVQMVRTKNITTVLNTSFIYSTD-GITWSLPS------------GYCEGFGSENNIIEF-NASLVNNIRNS----------GLRRSFETKDFGKTWTEFPPMDKKV--DNRNHGVQGSTITIPSG---NKLVAAHSSAQNK-NNDYTRSDISLYAHNLYSGEVKLIDDFYPKVGNASGAGYSCLSYRKNVDKETLYVVYEA-NGSIEFQDL--SRHLPVIKSYN-";
        String d4 = "---VIFRG-----------------------PDRIPSIVASSVTPGVVTAFAEKRVGGGDPGALSNTNDIITRTSRDGGITWDTELNLTEQINVS-DEFDFSDPRPIYDP--SSNTVLVSYARWP-TDAAQNGDRIKP-----WMPNGIFYSVYDVASGNWQAPI---------------VNPGPGHGITLTRQQNISGSQNGRLIYPAIVLDR----FFLNVMSIYSDDGGSNWQTGSTLPIPFRWKSSSILETLEPSEADMVELQNGDLLLTARLDFNQIVNGVNYSPRQQFLSKDGGITWSLLEANNANVFSNISTGTVDASITRFEQSDGS--HFLLFTNPQGNPAGTNGRQNLGLWFSFDEGVTWKGPIQLVNGA-----SAYSDIYQLD---SENAIVIVETDNSNMRILRMPITLLKQKLTLSQN";
        
        //prediciton
        //reference

        AliValiAlg test = new AliValiAlg(a4, b4, c4, d4);

        System.out.println(test.getSensi());
        System.out.println(test.getSpeci());
        System.out.println(test.getCover());
        System.out.println(test.getMeanS());
        System.out.println(test.getInver());
        
        /*
           
        String a5 = "CCCCCCHHHHHHCCCCCC";
        String b5 = "---CCCHHCHCHCCC---";
        
        String a6 = "CCCHHHHHHCCC";
        String b6 = "CCHHHHHHHHCC";
        
        String a7 = "CCCCCHHHHHCCCEEEEECCEEEECHHHHHHEEECCCCHEEECC";
        String b7 = "CCCCCHHHHHCCCEEEEECCEEEECHHHHHHEEECCCCHEEECC";
        
        String b8 = "--------CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHHHHHCHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC--------";
        String a8 = "CECCCCCCCCCCCCCCCCCCEHHHHHHHHHHHHHHHHHCCCCCCHHHHHCCCCCCCCCCECCCCHHHHHHHHHHHHHCCCCCCCCCCCCCCCCEEEEEEEECCEEEEEEEEECCEEEEEEEEECCCCCCCCHHHHHHHHHHHHHHHHHHHHCCCCEEEECECHHHHHHHHHHHCCCCCCCEEEECCCCCHHHHCCC";

        String a9 = "CCCCCCCCHHHHHHHCCHHHHHHHCCCCCEEEEEECCCEECCCEECCEEEEEEEEEEECCCCEEEEEEEEECCCCCCCEEEEEEEEEECCCCCCCCCEEEEECCCCCEEEEEEEEEECCEEEEEECCCCCCCCEEEEEECCCCEEEHHHHHHHHHHCCCCCCEECCCHHHHC";
        String b9 = "--------HHCCCCCCHCHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHCCCHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCHHCCCCCCCCCCCCCCC--------";
        
        //prediciton
        //reference
         
        StrucValiAlg test2 = new StrucValiAlg (a9,b9);
        
        System.out.println(test2.getQ3());
        System.out.println(test2.getSOV());
        
        System.out.println(test2.getQH());
        System.out.println(test2.getQE());
        System.out.println(test2.getQC());

        System.out.println(test2.getSOVH());
        System.out.println(test2.getSOVE());
        System.out.println(test2.getSOVC());
        */
    }
}
