#! /usr/bin/perl -w

# imports
use strict;
use LWP::Simple;
use DBI;

# subs


# open connection to Database
my $db = DBI->connect('DBI:mysql:bioprakt4;host=mysql2-ext.bio.ifi.lmu.de', 'bioprakt4', 'vGI5GCMg0x') or die "Could not connect to database: $DBI::errstr";

# loop over all files
# in each directory theres a ali and a tem file (ali = Sequence-Alignment, tem = secondary structure)
@homstrandFiles = </home/proj/biocluster/praktikum/bioprakt/Data/HOMSTRAD/*>;
foreach $directory (@homstrandFiles) {
  # for all available files
  @alignmentFiles = </home/proj/biocluster/praktikum/bioprakt/Data/HOMSTRAD/$directory/*.ali>;
  @structureFiles = </home/proj/biocluster/praktikum/bioprakt/Data/HOMSTRAD/$directory/*.tmp>;
  
  # save secondary structures
  foreach $struct (@structureFiles) {
    # open file
    open FILEHANDLE, "<".$struct or die("can't open file!");
    my @lines = <FILEHANDLE>;
    close(FILEHANDLE);
    
    # file layout (tem)
    # >SeqName
    # Type (sequence, secondary structure and phi angle, etc.)
    # Sequence
    # The file might more than one time contain each SeqName,
    # so that all information could be given for each Sequence.
    
    # file layout (ali)
    # >SeqName (might refer tem-file)
    # Some Information about the Sequence
    # Sequence with gap that aligns the other Sequences in the file
    
    # read lines
    my %seqHashSet = ();
    foreach my $line(@lines) {
      
    }
  }
  # save alignments
  foreach $align (@alignmentFiles) {
    # get lines from file
    open FILEHANDLE, "<".$align or die("can't open file!");
    my @lines = <FILEHANDLE>;
    close(FILEHANDLE);
    
    # read 
    
    
    
  }
  
}


