#!/usr/bin/perl
use strict;

die "Enter the path to the file as parameter!" unless defined $ARGV[0];
open FILE, $ARGV[0] or die "File does not exist / not a correct path!";

my @seq = <FILE>;#read the input file into a list
my $sequence;

for(my $i=0;$i<scalar(@seq);$i++){#convert the list to a string without linebreaks
        $sequence .= $seq[$i];
        chomp $sequence;
}

my $stopCounter = 0;
my @ORFpositions;

while($sequence =~ /((TAG|TAA|TGA))/g){# I did not figure how to use "regex lookarounds", so I first look for all occurences of a stop codon
	$stopCounter++;
	pos $sequence = (pos $sequence) - length($1) + 1;
	push(@ORFpositions, pos $sequence);
}

my %ORF;
my %ORFlength;
my $orfCounter = 0;
my $maxORFlength = 0;

for(my $i=0; $i<scalar(@ORFpositions);$i++){#then I look at all stop codon positions
	for(my $j=$ORFpositions[$i]-3;$j>=($ORFpositions[$i]%3);$j-=3){#and look at the triplets following to the left in 5' direction
		my $currentCodon = substr($sequence, $j-3, 3);
		if($currentCodon eq "TAA" || $currentCodon eq "TGA" || $currentCodon eq "TAG"){#if there is another stopcodon 3*n positions away
			last;#then the currently considered stop codon cannot be a stop codon of an ORF
		}
		if($currentCodon eq "ATG"){#if there is no stop codon in 3*n space to the left, but a start codon, then we have found one ORF
			$ORF{$j} = $ORFpositions[$i]+2;#store the beginning and end of the ORF in a hash
			$ORFlength{$ORFpositions[$i]+2-$j+3} += 1;
			$orfCounter++;#count the number of ORFs
			if($maxORFlength<($ORFpositions[$i]+2-$j+3)){#evaluate the longest ORF, which is neccessary later for the histogram
				$maxORFlength = $ORFpositions[$i]+2-$j+3;
			}
			last;
		}
	}
}

#while ( (my $k,my $v) = each %ORF ) {#you may print the bounds and lengths of the reading frames
#    print "$k => $v (".($v-$k)."), ";
#}
print "$stopCounter occurences of stop codon, $orfCounter occurences of an ORF, maxORFlength: $maxORFlength\n";

###### make histogram:
my $sumOfORFlength;
my $nonemptyORFs = 0;
for(my $i=0;$i<$maxORFlength;$i++){
	my $bar = "";
	$sumOfORFlength += $ORFlength{$i};
	for(my $j=0;$j<$ORFlength{$i};$j+=2){
		$bar.="x";
	}
	print "$i: $bar\n" unless $bar eq "";
	$nonemptyORFs++ unless $bar eq "";
}
print "sum: $sumOfORFlength\n";
print "$stopCounter occurences of stop codon, $orfCounter occurences of an ORF, maxORFlength: $maxORFlength, average length: ".($sumOfORFlength/$nonemptyORFs)."\n";
print "1 x means there are 2 ORFs of the respective length, ORFs with lengt 0 are overridden by the histogram.\n";

