INSERT INTO DB (`Name`) VALUES("SwissProt");
INSERT INTO DB (`Name`) VALUES("NCBI");
INSERT INTO DB (`Name`) VALUES("HOMSTRAD");
INSERT INTO DB (`Name`) VALUES("PDB");
INSERT INTO DB (`Name`) VALUES("Unknown");