#!/usr/bin/perl -w
use strict;
use Getopt::Std;
my $argc = @ARGV;
die "Usage: $0 <Organism name> [-r]\n\tIf -r is given the argument is interpreted as regex" unless $argc >= 1;
my $organismName = $ARGV[0];
my $organismIsRegex = 0;
if ($argc == 2) {
	if($ARGV[1] eq "-r") {
		print STDERR "Interpreting organism as regular expression...\n";
		$organismIsRegex = 1;
	}
}
#Donwload the genome report
use LWP::Simple;
my $genomeReport= get "ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt";
#Alternate method
#my $genomeReport= `wget -qO- ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt`;
if(!$genomeReport) {
	die "Could not download NCBI genome report!\n";
}
#Find the line(s) with the organism
foreach my $line (split /\n/ ,$genomeReport) {
	chomp $line;
	if($organismIsRegex) {
		if($line =~ m/^($organismName)\t/g) {
			my $currentOrganism = substr($line, 0, index($line, '	'));
			if($line =~ m/^([^\t]+\t){5}([\d.]+)/) {
				print "Genome of '$currentOrganism' has length $2 Mb\n";
			}
		}
	} else {
		if($line =~ m/^\Q$organismName)\E\t/g) {
			my $currentOrganism = substr($line, 0, index($line, '	'));
			if($line =~ m/^([^\t]+\t){5}([\d.]+)/) {
				print "Genome of '$currentOrganism' has length $2 Mb\n";
			}
		}
	}
}