#!/usr/bin/perl -w
use strict;
use Getopt::Std;
my %options=();
getopts("r",\%options);

my $argc = @ARGV;
die "Usage: $0 <Organism name> [-r]\n\tIf -r is given the argument is interpreted as regex" unless $argc >= 1;
my $organismName = $ARGV[0];
my $organismIsRegex = defined $options{r};

sub downloadGenomeReport {
	 use Net::FTP;
	my $ftp = Net::FTP->new("ftp.ncbi.nlm.nih.gov", Debug => 0,  Passive => 1) or die "Cannot connect to ftp.ncbi.nlm.nih.gov: $@";
	$ftp->login("anonymous",'-anonymous@') or die "Cannot login anonymously ", $ftp->message;
	$ftp->cwd("/genomes") or die "Cannot CWD to genomes ", $ftp->message;
	$ftp->cwd("GENOME_REPORTS") or die "Cannot CWD to genomes ", $ftp->message;
	$ftp->get("prokaryotes.txt") or die "FTP download failed: ", $ftp->message; # Downloads the file to the current local CWD
	$ftp->quit;
	#Read the file
	open FILE, "prokaryotes.txt" or die "Couldn't open prokaryotes.txt: $!";
	my $genomeReportContent = <FILE>;
	close FILE;
	#Delete the file
	unlink("prokaryotes.txt");
	#Return it
	print $genomeReportContent;
	$genomeReportContent;
}
#Donwload the genome report
use LWP::Simple;
#my $genomeReport= get "ftp://ftp.ncbi.nlm.nih.gov/genomes/GENOME_REPORTS/prokaryotes.txt";
#Alternate method that also works on CIP
my $genomeReport= downloadGenomeReport();
print $genomeReport;
if(!$genomeReport) {
	die "Could not download NCBI genome report!\n";
}
#Find the line(s) with the organism
foreach my $line (split /\n/ ,$genomeReport) {
	chomp $line;
	if($organismIsRegex) {
		if($line =~ m/^($organismName)\t/g) {
			my $currentOrganism = substr($line, 0, index($line, '	'));
			if($line =~ m/^([^\t]+\t){5}([\d.]+)/) {
				print "Genome of '$currentOrganism' has length $2 Mb\n";
			}
		}
	} else {
		if($line =~ m/^\Q$organismName)\E\t/g) {
			my $currentOrganism = substr($line, 0, index($line, '	'));
			if($line =~ m/^([^\t]+\t){5}([\d.]+)/) {
				print "Genome of '$currentOrganism' has length $2 Mb\n";
			}
		}
	}
}