#!/bin/bash

echo -e "reset
set terminal pngcairo  transparent enhanced font \"arial,10\" fontscale 1.0 size 500, 350 
set output 'heatmaps.1.png'
unset key
set view map
set xtics border in scale 0,0 mirror norotate  offset character 0, 0, 0 autojustify
set ytics border in scale 0,0 mirror norotate  offset character 0, 0, 0 autojustify
set ztics border in scale 0,0 nomirror norotate  offset character 0, 0, 0 autojustify
set nocbtics
set rtics axis in scale 0,0 nomirror norotate  offset character 0, 0, 0 autojustify
set title \"Heat Map\" 
set xrange [ 0.0 : 300.0 ] noreverse nowriteback
set yrange [ 0.0 : 300.0 ] noreverse nowriteback
set cblabel \"Score\" 
set cbrange [ 0.00000 : 10.00000 ] noreverse nowriteback
set palette rgbformulae -8, 2, -8
splot 'DistanceMatrix_3H9U' matrix with image" > data

gnuplot < data

rm data
