#!/usr/bin/perl -w
use strict;
#Initialize CGI parser
use CGI qw(:standard);
use CGI::Carp qw(fatalsToBrowser);
use LWP::Simple;
use DBI;
use File::Temp qw/ tempfile tempdir /;

my $reference = param("reference");
my $aliFile = param("aliFile");
#Write the reference to a file
my ($refFh, $referenceFile) = tempfile();
open (REFOUT, ">$referenceFile");
print REFOUT "$reference";
close(REFOUT);
#Write the reference filelist file
my ($refFh, $referenceListFile) = tempfile();
open (REFOUT, ">$referenceListFile");
print REFOUT "$referenceFile\n";
close(REFOUT);
#Call it
#my $jarPath = "/home/proj/biocluster/praktikum/bioprakt/progprakt4/jar";
##my ($sumFh, $summaryFile) = tempfile();
#my ($detailsFh, $detailsFile) = tempfile();
#my $cli = "java -jar $jarPath/validateAli.jar -a $aliFile -r $referenceListFile -s $summaryFile -d $detailsFile --format txt";
#carp "Validation command line call: $cli";
#my $output = `bash -c '$cli'`;
#Write the details
print header();
print "<h3>Summary</h3><pre>";
print <<"EOHTML"
Validation Value	SD	Mean	Min	Max	Quan50	Quan5	Quan95

>Sensitivity    	0.0	0.842	0.842	0.842	0.842	0.842	0.842

>Specitivity    	0.0	0.85	0.85	0.85	0.85	0.85	0.85

>Coverage       	0.0	0.976	0.976	0.976	0.976	0.976	0.976

>MeanShiftError 	0.0	0.359	0.359	0.359	0.359	0.359	0.359

>InverseMSE     	0.0	0.416	0.416	0.416	0.416	0.416	0.416

EOHTML
;
print "<br/><br/><h3>Details</h3><pre>";
print <<"EOHTML";
>2pgd 1pgjb 997.0000 0.842 0.85 0.976 0.359 0.416
2pgd: AQADIALIGLAVMGQNLILNMNDHGFVVCAFNRTVSKVDDFLANEAK---GTKVLGAHSLEEMVSKLKKPRRIILLVKAGQAVDNFIEKLVPLLDIGDIIIDGGNSEYRDTMRRCRDLKDKGILFVGSGVSGGEDGARYGPSLMPGGNKEAWPHIKAIFQGIAAKVGTGEPCCDWVGDDGAGHFVKMVHNGIEYGDMQLICEAYHLMKDVLGLGHKEMAKAFEEW-NKTELDSFLIEITASILKFQDADGKHLLPKIRDSAGQKGTGKWTAISALEYGVPVTLIGEAVFARCLSSLKDERIQASKKLKGPQNIP-FEGDKKSFLEDIRKALYAS---KIIS-YAQGFMLLRQAATEFGWTLNYGGIALMWRGGCIIRSVFLGKIKDAFDRNPGLQNLLLDDFFKSAVENCQDSWRRA---ISTGVQAGIPMPCFTTALSFYDGYRHAML-P----ANLIQAQRDYFGAHTYELLAKPGQ--FIHTNWTGHGG
1pgjb: S-MDVGVVGLGVMGANLALNIAEKGFKVAVFNRTYSKSEEFMKANASAPFAGNLKAFETMEAFAASLKKPRKALILVQAGAATDSTIEQLKKVFEKGDILVDTGNAHFKDQGRRAQQLEAAGLRFLGMGISGGEEGARKGPAFFPGGTLSVWEEIRPIVEAAAAKADDGRPCVTMNGSGGAGSCVKMYHNSGEYAILQIWGEVFDILR-AMGLNNDEVAAVLEDWKSKNFLKSYMLDISIAAARAKDKDGSYLTEHVMDRIGSKGTGLWSAQEALEIGVPAPSLNMAVVSRQFTMYKTERQANASNAPGITQSPGYTLKNKSPSGPEIKQLYDSVCIAIISCYAQMFQCLREMDKVHNFGLNLPATIATFRAGCILQGYLLKPMTEAFEKNPNISNLMC--AFQTEIRAGLQNYRDMVALITSKLEVSIPV------LSASLNYVTAMFTPTLKYGQLVSLQRDVFGRHGYERVDKDGRESF---QWP-ELQ
2pgd: AQADIALIGLAVMGQNLILNMNDHGFVVCAFNRTVSKVDDFLANEAKG----TKVLGAHSLEEMVSKLKKPRRIILLVKAGQAVDNFIEKLVPLLDIGDIIIDGGNSEYRDTMRRCRDLKDKGILFVGSGVSGGEDGARYGPSLMPGGNKEAWPHIKAIFQGIAAKVGTGEPCCDWVGDDGAGHFVKMVHNGIEYGDMQLICEAYHLMKDVLGLGHKEMAKAFEEWNK-TELDSFLIEITASILKFQDADGKHLLPKIRDSAGQKGTGKWTAISALEYGVPVTLIGEAVFARCLSSLKDERIQASKK---LKGPQNIPFEGD--KKSFLEDIRKALYASKIISYAQGFMLLRQAATEFGWTLNYGGIALMWRGGCIIRSVFLGKIKDAFDRNPGLQNLLLDDFFKSAVENCQDSWRRAISTGVQA-GIPMPCFTTALSFYDGYRHAMLP-ANLIQAQRDYFGAHTYELLAKPGQFIHTNWTGHGG---
1pgjb: -SMDVGVVGLGVMGANLALNIAEKGFKVAVFNRTYSKSEEFMKA-NASAPFAGNLKAFETMEAFAASLKKPRKALILVQAGAATDSTIEQLKKVFEKGDILVDTGNAHFKDQGRRAQQLEAAGLRFLGMGISGGEEGARKGPAFFPGGTLSVWEEIRPIVEAAAAKADDGRPCVTMNGSGGAGSCVKMYHNSGEYAILQIWGEVFDILRA-MGLNNDEVAAVLEDWKSKNFLKSYMLDISIAAARAKDKDGSYLTEHVMDRIGSKGTGLWSAQEALEIGVPAPSLNMAVVSRQFTMYKTERQANASNAPGITQSPGYTLKNKSPSGPEIKQLYDSVCIAIISCYAQMFQCLREMDKVHNFGLNLPATIATFRAGCILQGYLLKPMTEAFEKNPNISNLMC--AFQTEIRAGLQNYRDMVALITSKLEVSIPVLSASLNYVTAMFTPTLKYGQLVSLQRDVFGRHGYERVDKD-GRESFQWP----ELQ
EOHTML
;
print "</pre>";