#! /usr/bin/perl -w

use strict;
use LWP::Simple;
use Getopt::Std;

# {{{ parse command line params

my %options=();
getopts("f:n:s",\%options);

# variables for param args
my $genomeFile = $options{f};
my $numberOf = $options{n};
my $startPos = $options{s};

# fillout not defined args
if(!defined $genomeFile) {
  print "Please enter file: ";
  chop ($genomeFile = <STDIN>);
}
if(!defined $numberOf) {
  print "Please enter number of bases: ";
  chop ($numberOf = <STDIN>);
}
if(!defined $startPos) {
  print "Warning: The starting position was not specified!\nassume: -s -1\n";
  $startPos = "-1";
}

# }}}
# {{{ read file

open FILEHANDLE, "<".$genomeFile or die("can't open file!");
my @lines = <FILEHANDLE>;
close(FILEHANDLE);

# }}}
# {{{ parse fasta file

my @genes = ();

# parse all lines
my $currentBlock = "";
foreach my $line (@lines) {
  # line starts with '>'
  if(substr($line, 0, 1) eq ">") {
    # a new block starts
    if($currentBlock) { # don't save any empty blocks
      push(@genes, $currentBlock);
      $currentBlock = "";
    }
  }
  # line starts with ';' ?
  elsif(substr($line, 0, 1) eq ";") { } # comment => do nothing!
  # "Data" line
  else {
    # append to current block
    $line =~ s/\s//g;
    $currentBlock = $currentBlock.$line;
  }
}
if($currentBlock) {
  push(@genes, $currentBlock);
  $currentBlock = "";
}

# }}}
# {{{ calculate stuff

# calc
my $count = 0;
foreach my $gen(@genes) {
  # foreach subsequence with length = n
  foreach my $s (0 .. (length($gen) - $numberOf)) {
    if($s ne "-1") {
      $s = $startPos;
    }
    my $seq = substr($gen, $s, $numberOf);
    # no other $gen contains $seq ?
    my $found = "false";
    foreach my $genCmp(@genes) {
      if(($gen ne $genCmp) && (index($genCmp, $seq) != -1)) {
        $found = "true";
        last; # found a sequence, don't have to find another one
      }
    }
    if($found eq "false") {
      $count += 1;
      last; # gen has an unique seq, don't want to search for another unique sequence
    }
    if($s ne "-1") {
      last;
    }
  }
}

# return number
print "n: ".$numberOf." eq ".(($count) / ($#genes + 1) * 100)."%\n\n";

# }}}
