#! /usr/bin/perl -wl
#warnings, newlines
use strict;

print STDERR "Enter nucleotide sequence in FASTA-format:";
my @lines = <STDIN>;
my $RNA = $lines[0];#save the head of the fasta file

die "Please supply a FASTA sequence on STDIN!\n" unless $RNA =~ m/^>/;

for(my $i=1;$i<scalar(@lines);$i++){
	for(my $j=0;$j<length($lines[$i]);$j++){
		if(substr($lines[$i],$j,1) eq "T"){
			$RNA.="U";
		}
		elsif(substr($lines[$i],$j,1) eq "t"){$RNA.="u";}
		else{
			$RNA.=substr($lines[$i],$j,1);
		}
	}
}

print "\nmRNA:\n".$RNA;

