#! /usr/bin/perl -wl
#warnings, newlines
use strict;

#The hash table has been copied from http://bioperl.wordpress.com/2011/04/14/genetic-code-perl-hash/
my(%genetic_code) = (
'UCA' => 'S', # Serine
'UCC' => 'S', # Serine
'UCG' => 'S', # Serine
'UCU' => 'S', # Serine
'UUC' => 'F', # Phenylalanine
'UUU' => 'F', # Phenylalanine
'UUA' => 'L', # Leucine
'UUG' => 'L', # Leucine
'UAC' => 'Y', # Tyrosine
'UAU' => 'Y', # Tyrosine
'UAA' => '_', # Stop
'UAG' => '_', # Stop
'UGC' => 'C', # Cysteine
'UGU' => 'C', # Cysteine
'UGA' => '_', # Stop
'UGG' => 'W', # Tryptophan
'CUA' => 'L', # Leucine
'CUC' => 'L', # Leucine
'CUG' => 'L', # Leucine
'CUU' => 'L', # Leucine
'CCA' => 'P', # Proline
'CAU' => 'H', # Histidine
'CAA' => 'Q', # Glutamine
'CAG' => 'Q', # Glutamine
'CGA' => 'R', # Arginine
'CGC' => 'R', # Arginine
'CGG' => 'R', # Arginine
'CGU' => 'R', # Arginine
'AUA' => 'I', # Isoleucine
'AUC' => 'I', # Isoleucine
'AUU' => 'I', # Isoleucine
'AUG' => 'M', # Methionine
'ACA' => 'T', # Threonine
'ACC' => 'T', # Threonine
'ACG' => 'T', # Threonine
'ACU' => 'T', # Threonine
'AAC' => 'N', # Asparagine
'AAU' => 'N', # Asparagine
'AAA' => 'K', # Lysine
'AAG' => 'K', # Lysine
'AGC' => 'S', # Serine
'AGU' => 'S', # Serine
'AGA' => 'R', # Arginine
'AGG' => 'R', # Arginine
'CCC' => 'P', # Proline
'CCG' => 'P', # Proline
'CCU' => 'P', # Proline
'CAC' => 'H', # Histidine
'GUA' => 'V', # Valine
'GUC' => 'V', # Valine
'GUG' => 'V', # Valine
'GUU' => 'V', # Valine
'GCA' => 'A', # Alanine
'GCC' => 'A', # Alanine
'GCG' => 'A', # Alanine
'GCU' => 'A', # Alanine
'GAC' => 'D', # Aspartic Acid
'GAU' => 'D', # Aspartic Acid
'GAA' => 'E', # Glutamic Acid
'GAG' => 'E', # Glutamic Acid
'GGA' => 'G', # Glycine
'GGC' => 'G', # Glycine
'GGG' => 'G', # Glycine
'GGU' => 'G'  # Glycine
);

print "Enter nucleotide sequence in FASTA-format:";
my @lines = <STDIN>;
my $fastaHeader = $lines[0];#get the first line of STDIN, which should be in FASTA-format
#check if the first line is in fasta-format, "die" otherwise:
die "Please supply a FASTA sequence on STDIN! (press Enter, then Ctrl+D when finished to close STDIN)\n" unless $fastaHeader =~ m/^>/;

my $protein1 = $lines[0];#append the head of the fasta file to each of the output strings protein1..6
my $protein2 = $lines[0];
my $protein3 = $lines[0];
my $protein4 = $lines[0];
my $protein5 = $lines[0];
my $protein6 = $lines[0]; 	

my $RNA;
for(my $i=1 ;$i<scalar(@lines);$i++){
	#for(my $j=0;$j<length($lines[$i]);$j++){
	$RNA.=$lines[$i];#build $RNA by concatenating all the input from STDIN
	chomp $RNA;
	#}
}
chomp $RNA;
print "RNA: ".$RNA;

die "Your file does not contain a correct RNA sequence\n" unless $RNA !~ m/[^AUGCaugc]/;#checks if the input is actually a RNA sequence

my $reverseRNA = reverse($RNA);#3 of the 6 frames are read from 3' to 5' (reverse), therefore we need as well the reversed $RNA -> $reverseRNA
chomp $reverseRNA;

for(my $i=0;$i<length($RNA)-2;$i+=3){#translation takes place in this loop (fasta head will be overridden)

	$protein1.=$genetic_code{substr($RNA,$i,3)};#lookup codons in hash %genetic_code
	$protein4.=$genetic_code{substr($reverseRNA,$i,3)};
	if(length($RNA) - $i >= 4) {#checks if there are still enough nucleotides "ahead" to form a triplet
		$protein2.=$genetic_code{substr($RNA,$i+1,3)};
		$protein5.=$genetic_code{substr($reverseRNA,$i+1,3)};
	}
	if(length($RNA) - $i >= 5) {#same as above
		$protein3.=$genetic_code{substr($RNA,$i+2,3)};
		$protein6.=$genetic_code{substr($reverseRNA,$i+2,3)};
	}
}
print "Frame 1:\n".$protein1."\n";#print all 6 frames
print "Frame 2:\n".$protein2."\n";
print "Frame 3:\n".$protein3."\n";
print "Frame 4:\n".$protein4."\n";
print "Frame 5:\n".$protein5."\n";
print "Frame 6:\n".$protein6."\n";

